Repository replicatedhq/kURL-testgrid, pull requests merged in 2023-03, with the labels that each got.

#217 chore: make image used during tests configurable.
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#220 exponentially backoff when failing to create VMIs, and report errors
  tgrun/pkg/runner/loop.go
  tgrun/pkg/runner/runner.go
Labels: bug::normal, type::bug

#221 fix exponential backoff code. Report failed instances as 'started' first to display logs.
  tgrun/pkg/runner/loop.go
  tgrun/pkg/runner/loop_test.go
  tgrun/pkg/runner/runner.go
Labels: bug::normal, type::bug

#222 show logs link if the failure reason was 'failed to create VMI'
  tgrun/pkg/runner/runner.go
  web/src/components/views/InstanceTable.jsx
Labels: bug::normal, type::bug

#218 chore: adding functions to test kots application installs and updates.
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore, type::tests

#226 chore: add missing quotes on echo command argument.
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#231 feat: disable yum repos on airgap installs
  tgrun/pkg/runner/vmi/embed/runcmd.sh
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore
