Repository replicatedhq/kURL-testgrid, pull requests merged in 2023-04, with the labels that each got.

#248 bug: add --namespace flag to kubectl kots command
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#250 randomize the order of tests within a run
  tgrun/pkg/scheduler/scheduler.go
Labels: type::feature

#251 chore(deps): bump kubevirt.io/client-go from 0.58.1 to 0.59.0
  go.mod
  go.sum
  tgrun/pkg/runner/cleanup.go
  tgrun/pkg/runner/metrics.go
  tgrun/pkg/runner/vmi/vmi.go
Labels: type::chore

#252 feat: use kurl prod if kurl.installerVersion is set
  tgrun/pkg/scheduler/scheduler.go
  tgrun/pkg/scheduler/types/types.go
Labels: type::chore

#253 feat: airgap kots integration test app
  tgrun/pkg/runner/vmi/embed/common.sh
  tgrun/pkg/runner/vmi/embed/runcmd.sh
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#254 fix: prefix exported vars with TESTGRID_ to avoid collisions
  tgrun/pkg/runner/vmi/embed/runcmd.sh
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#255 fix: kots test app failure checking endpoint
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#256 fix: fail download on error
  tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
  tgrun/pkg/runner/vmi/embed/runcmd.sh
  tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
Labels: type::chore

#261 fix: kurl integration test application get nginx service ip
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: bug::normal, type::bug

#262 fix: generic kurl integration test app airgap bundle url
  tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::chore

#269 fix: typos
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#270 fix: retry download and untar airgap files
  tgrun/pkg/runner/vmi/embed/common.sh
  tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
  tgrun/pkg/runner/vmi/embed/runcmd.sh
  tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
Labels: type::chore

#271 fix: omit last version in step upgrade bundle
  tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: type::chore

#275 chore: moving tgapi base image to debian buster
  tgapi/deploy/Dockerfile
Labels: type::chore
